name: pr-validation
on: 
    pull_request:
    types:
        - opened 
         -synchronize 
push: 
      branches:
       - develop

jobs: 

      pr-validation-job:
          runs-on: ubuntu-latest
          steps: 
           - name : Welcome steps
           #run ki command operation system ko jayegi (ubuntu ko )
          run: echo "welcome to github actions"